# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStart', models.DateTimeField()),
                ('dateFinish', models.DateTimeField()),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DriverTaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('odh', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TechOp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='drivertask',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esmc.Route'),
        ),
        migrations.AddField(
            model_name='drivertask',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esmc.DriverTaskStatus'),
        ),
        migrations.AddField(
            model_name='drivertask',
            name='techOp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esmc.TechOp'),
        ),
        migrations.AddField(
            model_name='drivertask',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esmc.Worker'),
        ),
    ]
